FROM ubuntu:latest

WORKDIR /home/aakash/Desktop/Delta

# Install necessary dependencies
RUN apt-get update && \
    apt-get install -y sudo && \
    apt-get clean && \
    apt-get install acl && \
    apt-get install -y vim && \
    apt-get install -y apache2 && \
    apt-get install -y apache2-utils && \
    rm -rf /var/lib/apt/lists/*

# Copy the server setup files to the container
COPY usergen.sh /home/aakash/Desktop/Delta/scripts
COPY domainPreference.sh /home/aakash/Desktop/Delta/scripts
COPY mentorAllocation.sh /home/aakash/Desktop/Delta/scripts
COPY displayStatus.sh /home/aakash/Desktop/Delta/scripts
COPY submitTask.sh /home/aakash/Desktop/Delta/scripts
COPY deRegister.sh /home/aakash/Desktop/Delta/scripts
COPY cronjob.sh /home/aakash/Desktop/Delta/scripts
COPY mentors.txt /home/aakash/Desktop/Delta/scripts
COPY mentees.txt /home/aakash/Desktop/Delta/scripts
COPY apache.sh /home/aakash/Desktop/Delta/scripts
COPY database.sh /home/aakash/Desktop/Delta/scripts
COPY setQuiz.sh /home/aakash/Desktop/Delta/scripts
COPY .bashrc /home/aakash/Desktop/Delta/scripts

# Running the setup scripts
RUN chmod +x /home/aakash/Desktop/Delta/scripts/usergen.sh
RUN chmod +x /home/aakash/Desktop/Delta/scripts/domainPreference.sh
RUN chmod +x /home/aakash/Desktop/Delta/scripts/mentorAllocation.sh 
RUN chmod +x /home/aakash/Desktop/Delta/scripts/displayStatus.sh 
RUN chmod +x /home/aakash/Desktop/Delta/scripts/submitTask.sh 
RUN chmod +x /home/aakash/Desktop/Delta/scripts/deRegister.sh 
RUN chmod +x /home/aakash/Desktop/Delta/scripts/cronjob.sh 
RUN chmod +x /home/aakash/Desktop/Delta/scripts/setQuiz.sh
RUN chmod +x /home/aakash/Desktop/Delta/scripts/apache.sh
RUN chmod +x /home/aakash/Desktop/Delta/scripts/database.sh
RUN mkdir /home/aakash/Desktop/Delta/scripts/shared
RUN scripts/usergen.sh

# Expose the required ports
EXPOSE 80

# Set the entry point to keep the container running
CMD ["tail", "-f", "/dev/null"]

