version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: quiz_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quiz_game
      MYSQL_USER: aakash
      MYSQL_PASSWORD: db_pass
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: aakash
      DB_PASSWORD: db_pass
      DB_NAME: quiz_game
    ports:
      - "5555:5555"
